# Generated by Django 3.1.4 on 2020-12-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_auto_20201215_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ytube_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
