# Generated by Django 3.1.4 on 2020-12-21 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
