# Generated by Django 3.1.4 on 2020-12-21 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_auto_20201221_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
