# Generated by Django 3.1.4 on 2020-12-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0003_auto_20201216_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('nikon', 'nikon'), ('canon', 'canon'), ('fujifilm', 'fujifilm'), ('panasonic', 'panasonic'), ('kodak', 'kodak'), ('sony', 'sony')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('coding', 'coding'), ('gadget_review', 'gadget_review'), ('vlogs', 'vlogs'), ('comedy', 'comedy'), ('gaming', 'gaming'), ('cooking', 'cooking'), ('music', 'music'), ('lifestyle', 'lifestyle')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('solo', 'solo'), ('small', 'small'), ('large', 'large')], max_length=255),
        ),
    ]
